Support configurable emulator screen resolution
google/android-emulator-container-scripts pull request #225
Opened 2020-12-18 07:00 UTC by jnhyperion

Added emulator screen resolution configuration options in interactive mode.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/20297196/102582547-cc388a00-413d-11eb-82ff-223d89838c4c.png">

2020-12-22 19:40 UTC, pokowaka requested changes
- Would you mind moving the UI pieces to emu_downloads_menu.py?
- Would it be useful to have a set of default devices? (Pixel2, Pixel3, etc?) right now we have no way of specifying width/height/dpi from commandline.

2020-12-23 03:13 UTC, jnhyperion commented
> * Would you mind moving the UI pieces to emu_downloads_menu.py?
OK.
> * Would it be useful to have a set of default devices? (Pixel2, Pixel3, etc?) right now we have no way of specifying width/height/dpi from commandline.

I thought about it before, there are 2 reasons why I prefer to enter width/height/dpi from command line:

1. user could have some requests of customized devices, they have various width/height/dpi, we can not list all the hardware profile
2. Pixel2 is hard coded in many code pieces, make it a variable will have many modifications

What do you think?

2020-12-23 04:06 UTC, pokowaka commented
> > * Would you mind moving the UI pieces to emu_downloads_menu.py?
> >   OK.
> > * Would it be useful to have a set of default devices? (Pixel2, Pixel3, etc?) right now we have no way of specifying width/height/dpi from commandline.
> 
> I thought about it before, there are 2 reasons why I prefer to enter width/height/dpi from command line:
> 
> 1. user could have some requests of customized devices, they have various width/height/dpi, we can not list all the hardware profile
> 2. Pixel2 is hard coded in many code pieces, make it a variable will have many modifications
> 
> What do you think?

You are absolutely right. I should have prefixed it with would you like us to make those changes (different device profiles)

2020-12-23 05:17 UTC, jnhyperion commented
@pokowaka  sure, it would be great.

2026-05-16 21:19 UTC, jpcottin commented
@jnhyperion — thanks for the contribution, and apologies it sat without action for so long. Closing rather than asking for a rebase because the right path forward looks different from the implementation here:

- The diff patches `emu/templates/avd/Pixel2.avd/config.ini`, which was renamed to `MediumPhone.avd/config.ini` in #402 (merged today) — so a mechanical rebase can't recover that file.
- The non-interactive `emu-docker create` (which most automation uses) wouldn't get the feature with the current shape; a CLI flag like `--screen-resolution WxHxDPI` usable from both flows would be more broadly useful, and wouldn't need the new `consolemenu` dependency.
- A few unrelated changes (`iputils-ping` install, commented-out `EXPOSE 5554` / `EXPOSE 8554` — those ports are actively used) would need to be split out separately.

If configurable resolution is still useful to you, please open a new issue describing the feature request — a CLI-flag-based approach usable from both the scripted and interactive flows. Small enough that anyone (including a fresh attempt by you) could pick it up.

The code and instructions have changed substantially since this was filed, so a fresh thread will be easier to track.

2026-05-16 21:19 UTC, closed without merging